---
title: "joinXL Functions"
author: "Yvonne Glanville"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{joinXL Functions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## joinXL  functions perform 'SQL' type joins of 'Excel' files    

Calling any of these functions **fulljoinXL()**, **leftjoinXL()**, **rightjoinXL()**, **innerjoinXL()** 
will open a dialog box, which allows 2 '.xlsx' or '.xls' files to be opened.   

Follow prompts at the console to manipulate files.   
Console Prompt: Which file is your base (1 or 2)?   
**The values in the rows of the base file take precedence over those in the join file.**   

A common join column must be chosen for each file. This allows common columns with 
different naming conventions to be joined. 
 
---
## Minus Query   

Calling **minusXL()** opens a dialog box, which allows 2 '.xlsx' or '.xls' files to be opened.
At the console choose the source file, and then 2 operations are performed on the files.   

**Operation 1.** source file-minus-target file   
**Operation 2.** target file-minus-source file   

The Excel files are opened using the dialog box. At the console a source file is chosen,
and common columns in the source and target files are selected.   

**Output at the console**   
1. Preview of source file-minus-target file   
2. Preview of target file-minus-source file   
3. Preview of source file-minus-target file + target file-minus-source file   

**Output in working directory**   
sourcemMINUStarget.xlsx   
targetMINUSsource.xlsx   
rowsNOTduplicated.xlsx   

###**If the source and the target .xlsx files are identical, then the output files will be empty.**

